# Generated by Django 3.0.5 on 2020-06-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_movie_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewing',
            name='date',
            field=models.DateField(),
        ),
    ]
